/////////////////////////////////////////////////////////////////////////////////////////////
// Copyright 2026 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/////////////////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.205.0Release
// Tag = production/release/21.205.0-0-gb3c261eb
/////////////////////////////////////////////////////////////////////////////////////////////


#include <cmath>
#include <memory>

#include "fit_file_id_mesg.hpp"
#include "fit_hr_mesg.hpp"
#include "fit_record_mesg.hpp"
#include "fit_runtime_exception.hpp"
#include "fit_hr_to_record_message_plugin.hpp"

const long GAP_INCREMENT_MILLISECONDS = 250;
const float GAP_INCREMENT_SECONDS = GAP_INCREMENT_MILLISECONDS / 1000.0;
const long GAP_MAX_MILLISECONDS = 5000;
const long GAP_MAX_STEPS = GAP_MAX_MILLISECONDS / GAP_INCREMENT_MILLISECONDS;

class HeartRate
{
public:
    FIT_UINT8 bpm;
    fit::DateTime timestamp;
    HeartRate(FIT_UINT8 bpm, const fit::DateTime &timestamp);
    HeartRate(const HeartRate &other);
};

class HeartRateList
{
public:
    std::vector<HeartRate> hrList;

    HeartRateList();
    void AddHeartRate(FIT_UINT8 bpm, const fit::DateTime &timestamp);
    void AddHrMessage(fit::HrMesg const &hrMesg);

private:
    float anchorEventTimestamp;
    std::unique_ptr<fit::DateTime> anchorTimestamp;
};

namespace fit
{
    /**
     * Provides functionality to backfill record messages with hr data from HR mesg.
     *
     * The plugin matches the timestamp of record messages with the timestamps hr data
     * contained in the HR mesg.
     *
     * Requirements for correct operation:
     *    - HR data must be in the order of increasing timestamp
     *    - Record data must be in the order of increasing timestamp
     *    - The order of incoming HR and record mesgs may be independent of each other
     *    - The first HR mesg must contain a timestamp (with optional fractional_timestamp)
     *      which, in combination with the event_timestamps that mark the bpm data, provide the
     *      time that is used to match record data.
     *    - There must be an equal number of filtered_bpm fields and event_timestamp fields in each
     *      HR mesg; this number may change from message to message.
     *
     */
    HRToRecordMesgBroadcastPlugin::HRToRecordMesgBroadcastPlugin() : isActivityFile(false), heartRates(new HeartRateList()) {}

    HRToRecordMesgBroadcastPlugin::~HRToRecordMesgBroadcastPlugin() = default;

    /**
     * Peeks messages as they are being added to the buffer
     *
     * @param mesg the message that has just been buffered by BufferedMesgBroadcaster
     */
    void HRToRecordMesgBroadcastPlugin::OnIncomingMesg(const Mesg &mesg)
    {
        switch (mesg.GetNum())
        {
        case FIT_MESG_NUM_FILE_ID:
        {
            FileIdMesg fileIdMesg = FileIdMesg(mesg);
            if (fileIdMesg.GetType() == FIT_FILE_ACTIVITY)
                isActivityFile = true;
        }
        break;
        case FIT_MESG_NUM_HR:
            heartRates->AddHrMessage(HrMesg(mesg));
            break;
        default:
            break;
        }
    }
    /**
     * Matches record time ranges with all time matching HR mesgs and updates the
     * message stream for later broadcast to listeners.
     *
     * @param mesgs the message list that is about to be broadcast to all MesgListeners.  \
                    Note: Editing Mesg objects within mesgs will alter the messages   \
                    that are broadcast to listeners.
     *
     * DO NOT add or remove any messages to mesgs
     */
    void HRToRecordMesgBroadcastPlugin::OnBroadcast(std::vector<Mesg> &mesgs)
    {
        if (!isActivityFile || heartRates->hrList.size() == 0)
        {
            return;
        }

        int heartRateIndex = 0;
        std::unique_ptr<DateTime> recordRangeStartTime;

        for (int mesgCounter = 0; mesgCounter < mesgs.size(); ++mesgCounter)
        {
            Mesg &mesg = mesgs[mesgCounter];

            if (mesg.GetNum() == FIT_MESG_NUM_RECORD)
            {
                long hrSum = 0;
                long hrSumCount = 0;

                RecordMesg recordMesg = RecordMesg(mesg);
                DateTime recordRangeEndTime = DateTime(recordMesg.GetTimestamp());

                if (!recordRangeStartTime)
                {
                    recordRangeStartTime = std::unique_ptr<DateTime>(new DateTime(recordMesg.GetTimestamp()));
                }

                if (recordRangeStartTime->CompareTo(recordRangeEndTime) == 0)
                {
                    recordRangeStartTime->add((FIT_DATE_TIME)-1);
                    heartRateIndex = (heartRateIndex >= 1) ? heartRateIndex - 1 : 0;
                }

                bool findingInRangeHrMesgs = true;
                while (findingInRangeHrMesgs && heartRateIndex < heartRates->hrList.size())
                {
                    HeartRate &heartrate = heartRates->hrList[heartRateIndex];

                    // Check if the heartrate timestamp is gt record start time
                    // and if the heartrate timestamp is lte to record end time
                    if ((heartrate.timestamp.CompareTo(*recordRangeStartTime) > 0) && (heartrate.timestamp.CompareTo(recordRangeEndTime) <= 0))
                    {
                        hrSum += heartrate.bpm;
                        hrSumCount++;
                    }
                    // Check if the heartrate timestamp exceeds the record time
                    else if (heartrate.timestamp.CompareTo(recordRangeEndTime) > 0)
                    {
                        findingInRangeHrMesgs = false;

                        if (hrSumCount > 0)
                        {
                            FIT_UINT8 avgHr = static_cast<FIT_UINT8>(std::round(static_cast<float>(hrSum) / static_cast<float>(hrSumCount)));
                            mesg.SetFieldUINT8Value(RecordMesg::FieldDefNum::HeartRate, avgHr, 0, FIT_SUBFIELD_INDEX_MAIN_FIELD);
                        }

                        hrSum = 0;
                        hrSumCount = 0;

                        recordRangeStartTime = std::unique_ptr<DateTime>(new DateTime(recordRangeEndTime));

                        break;
                    }

                    heartRateIndex++;
                }
            }
        }
    }
} // namespace fit

// MARK: HeartRate

HeartRate::HeartRate(FIT_UINT8 bpm, const fit::DateTime &timestamp)
    : bpm(bpm), timestamp(timestamp)
{
}

HeartRate::HeartRate(const HeartRate &other)
    : bpm(other.bpm), timestamp(other.timestamp)
{
}

// MARK: HeartRateList

HeartRateList::HeartRateList()
{
    hrList = std::vector<HeartRate>();

    anchorEventTimestamp = 0.0;
    anchorTimestamp = nullptr;
}

void HeartRateList::AddHeartRate(FIT_UINT8 bpm, const fit::DateTime &timestamp)
{
    hrList.push_back(HeartRate(bpm, timestamp));
}

void HeartRateList::AddHrMessage(fit::HrMesg const &hrMesg)
{
    // Update HR timestamp anchor, if present
    if (hrMesg.GetTimestamp() != FIT_UINT32_INVALID)
    {
        anchorTimestamp = std::unique_ptr<fit::DateTime>(new fit::DateTime(hrMesg.GetTimestamp()));

        FIT_UINT16 fractional_timestamp_internal = hrMesg.GetFieldUINT16Value(fit::HrMesg::FieldDefNum::FractionalTimestamp, 0, FIT_SUBFIELD_INDEX_MAIN_FIELD);
        if (fractional_timestamp_internal != FIT_UINT16_INVALID)
        {
            anchorTimestamp->add(hrMesg.GetFractionalTimestamp());
        }

        if (hrMesg.GetNumEventTimestamp() == 1)
        {
            anchorEventTimestamp = hrMesg.GetEventTimestamp(0);
        }
        else
        {
            throw fit::RuntimeException("FIT HrToRecordMesgBroadcastPlugin Error: Anchor HR mesg must have exactly 1 event_timestamp");
        }
    }

    if (anchorTimestamp == nullptr)
    {
        // We cannot process any HR messages if we have not received a timestamp anchor
        throw fit::RuntimeException("FIT HrToRecordMesgBroadcastPlugin Error: No anchor timestamp received in a HR mesg before diff HR mesgs");
    }
    else if (hrMesg.GetNumEventTimestamp() != hrMesg.GetNumFilteredBpm())
    {
        throw fit::RuntimeException("FIT HrToRecordMesgBroadcastPlugin Error: HR mesg with mismatching count of event timestamp and filtered bpm");
    }

    for (int i = 0; i < hrMesg.GetNumEventTimestamp(); i++)
    {
        FIT_FLOAT32 eventTimestamp = hrMesg.GetEventTimestamp(i);

        // Check to see if the event timestamp rolled over
        if (eventTimestamp < anchorEventTimestamp)
        {
            if ((anchorEventTimestamp - eventTimestamp) > (1 << 21))
            {
                eventTimestamp += (1 << 22);
            }
            else
            {
                throw fit::RuntimeException("FIT HrToRecordMesgBroadcastPlugin Error: Anchor event_timestamp is greater than subsequent event_timestamp. This does not allow for correct delta calculation.");
            }
        }

        HeartRate currentHr = HeartRate(hrMesg.GetFilteredBpm(i), fit::DateTime(*anchorTimestamp));
        currentHr.timestamp.add(eventTimestamp - anchorEventTimestamp);

        // Carry the previous HR value forward across the gap to the current
        // HR value for up to 5 Seconds (5000ms) in 250ms increments
        if (!hrList.empty())
        {
            HeartRate previousHr = hrList.back();
            long long currentTimestampMs = static_cast<long long>(currentHr.timestamp.GetTimeStamp()) * 1000 +
                                           static_cast<long long>(currentHr.timestamp.GetFractionalTimestamp() * 1000);
            long long previousTimestampMs = static_cast<long long>(previousHr.timestamp.GetTimeStamp()) * 1000 +
                                            static_cast<long long>(previousHr.timestamp.GetFractionalTimestamp() * 1000);
            long long gapInMilliseconds = std::abs(currentTimestampMs - previousTimestampMs);

            long step = 1;
            while (gapInMilliseconds > GAP_INCREMENT_MILLISECONDS && step <= GAP_MAX_STEPS)
            {
                HeartRate gapHr = HeartRate(previousHr);
                gapHr.timestamp.add(GAP_INCREMENT_SECONDS * step);
                hrList.push_back(gapHr);

                gapInMilliseconds -= GAP_INCREMENT_MILLISECONDS;
                step++;
            }
        }

        hrList.push_back(currentHr);
    }
}
