/////////////////////////////////////////////////////////////////////////////////////////////
// Copyright 2026 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/////////////////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.205.0Release
// Tag = production/release/21.205.0-0-gb3c261eb
/////////////////////////////////////////////////////////////////////////////////////////////


#if !defined(FIT_HR_TO_RECORD_MESSAGE_PLUGIN_HPP)
#define FIT_HR_TO_RECORD_MESSAGE_PLUGIN_HPP

#include <memory>
#include <vector>

#include "fit.hpp"
#include "fit_date_time.hpp"
#include "fit_mesg_broadcast_plugin.hpp"

class HeartRateList;

namespace fit
{

    class HRToRecordMesgBroadcastPlugin : public MesgBroadcastPlugin
    {
    public:
        HRToRecordMesgBroadcastPlugin();
        ~HRToRecordMesgBroadcastPlugin();

        void OnBroadcast(std::vector<Mesg> &mesgs);
        void OnIncomingMesg(const Mesg &mesg);

        //  Plugins are not designed to be copied
        HRToRecordMesgBroadcastPlugin &operator=(const HRToRecordMesgBroadcastPlugin &) = delete;
        HRToRecordMesgBroadcastPlugin(const HRToRecordMesgBroadcastPlugin &) = delete;

    private:
        FIT_BOOL isActivityFile;
        std::unique_ptr<HeartRateList> heartRates;
    };
} // namespace fit

#endif // defined(FIT_HR_TO_RECORD_MESSAGE_PLUGIN_HPP)
