/////////////////////////////////////////////////////////////////////////////////////////////
// Copyright 2026 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/////////////////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.205.0Release
// Tag = production/release/21.205.0-0-gb3c261eb
/////////////////////////////////////////////////////////////////////////////////////////////


#if !defined(FIT_SLEEP_DISRUPTION_SEVERITY_PERIOD_MESG_LISTENER_HPP)
#define FIT_SLEEP_DISRUPTION_SEVERITY_PERIOD_MESG_LISTENER_HPP

#include "fit_sleep_disruption_severity_period_mesg.hpp"

namespace fit
{

class SleepDisruptionSeverityPeriodMesgListener
{
public:
    virtual ~SleepDisruptionSeverityPeriodMesgListener() {}
    virtual void OnMesg(SleepDisruptionSeverityPeriodMesg& mesg) = 0;
};

} // namespace fit

#endif // !defined(FIT_SLEEP_DISRUPTION_SEVERITY_PERIOD_MESG_LISTENER_HPP)
