/////////////////////////////////////////////////////////////////////////////////////////////
// Copyright 2023 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/////////////////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.101Release
// Tag = production/release/21.101.00-0-gceb92d5
/////////////////////////////////////////////////////////////////////////////////////////////


#if !defined(FIT_BUFFERED_RECORD_MESG_HPP)
#define FIT_BUFFERED_RECORD_MESG_HPP

#include "fit_record_mesg.hpp"

namespace fit
{

class BufferedRecordMesg : public RecordMesg
{
};

} // namespace fit

#endif // !defined(FIT_BUFFERED_RECORD_MESG_HPP)
