/////////////////////////////////////////////////////////////////////////////////////////////
// Copyright 2026 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/////////////////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.205.0Release
// Tag = production/release/21.205.0-0-gb3c261eb
/////////////////////////////////////////////////////////////////////////////////////////////


#if !defined(FIT_FACTORY_HPP)
#define FIT_FACTORY_HPP

#include <string>
#include "fit_mesg.hpp"

namespace fit
{

class Factory
{
public:
    static Mesg CreateMesg(Mesg mesg);
private:
};

} // namespace fit

#endif // !defined(FIT_FACTORY_HPP)
